//! The dashboard's pages and their assets, embedded in the binary so the
//! server runs from one file with nothing to install beside it.

use super::read;
use warp::{Filter, Reply};

const OVERVIEW: &str = include_str!("../../static/index.html");
const PEOPLE: &str = include_str!("../../static/people.html");
const ISLAND: &str = include_str!("../../static/island.html");
const CREATOR: &str = include_str!("../../static/creator.html");
const NOT_FOUND: &str = include_str!("../../static/not-found.html");

const HTML: &str = "text/html; charset=utf-8";
const JS: &str = "text/javascript; charset=utf-8";
const CSS: &str = "text/css; charset=utf-8";

/// The files under `/static/`. Keeping them in one table means a new asset is
/// one line here rather than a new route.
pub const ASSETS: [(&str, &str, &str); 6] = [
    ("style.css", include_str!("../../static/style.css"), CSS),
    ("app.js", include_str!("../../static/app.js"), JS),
    ("overview.js", include_str!("../../static/overview.js"), JS),
    ("people.js", include_str!("../../static/people.js"), JS),
    ("island.js", include_str!("../../static/island.js"), JS),
    ("creator.js", include_str!("../../static/creator.js"), JS),
];

/// Pages change whenever the binary does, so they are revalidated every time;
/// assets are embedded in that same binary, so a short cache is safe and keeps
/// a reload from refetching the stylesheet.
const PAGE_CACHE: &str = "no-cache";
const ASSET_CACHE: &str = "public, max-age=600";

fn served(body: &'static str, content_type: &'static str, cache: &'static str) -> impl warp::Reply {
    warp::reply::with_header(
        warp::reply::with_header(body, "content-type", content_type),
        "cache-control",
        cache,
    )
}

fn page(body: &'static str) -> impl warp::Reply {
    served(body, HTML, PAGE_CACHE)
}

/// Which island the pages this server sends should talk to.
///
/// Empty -- the ordinary case -- means the server that sent them, which is
/// what these pages did for as long as there was only one machine. A value
/// here is how a *frontend* is deployed against a backend somewhere else:
/// the pages are served from one host and every request goes to another.
///
/// Written into `/static/config.js` rather than into the pages, so the
/// pages stay identical bytes whoever serves them and a deployment is one
/// generated file.
pub type Backend = Option<String>;

/// The script that tells a page which island it is looking at.
///
/// Generated rather than embedded, and JSON-encoded rather than quoted by
/// hand: a backend address is configuration from a command line, and
/// pasting it into JavaScript with quotes around it is how a value with a
/// quote in it stops being a value.
fn config_js(backend: &Backend) -> String {
    let value = serde_json::to_string(backend.as_deref().unwrap_or(""))
        .unwrap_or_else(|_| "\"\"".to_string());
    format!(
        "// Generated by `island serve`. Which island these pages read.\n\
         // Empty means the server that sent them.\n\
         window.ISLAND_BACKEND = {value};\n"
    )
}

pub fn routes() -> impl Filter<Extract = (impl Reply,), Error = std::convert::Infallible> + Clone {
    routes_for(None)
}

/// The pages, told which island to read.
pub fn routes_for(
    backend: Backend,
) -> impl Filter<Extract = (impl Reply,), Error = std::convert::Infallible> + Clone {
    let overview = warp::path::end().and(read()).map(|| page(OVERVIEW));
    let people = warp::path!("people").and(read()).map(|| page(PEOPLE));
    let island = warp::path!("island").and(read()).map(|| page(ISLAND));
    let creator = warp::path!("creator").and(read()).map(|| page(CREATOR));
    // Generated, so it is not in the `ASSETS` table, and never cached:
    // it is the one file whose contents depend on how this server was
    // started, and a browser holding yesterday's copy would be reading
    // yesterday's island.
    let config = {
        let body = config_js(&backend);
        warp::path!("static" / "config.js")
            .and(read())
            .map(move || {
                warp::reply::with_header(
                    warp::reply::with_header(body.clone(), "content-type", JS),
                    "cache-control",
                    "no-store",
                )
            })
    };

    let assets = warp::path!("static" / String)
        .and(read())
        .and_then(|name: String| async move {
            match ASSETS.iter().find(|(asset, _, _)| *asset == name) {
                Some((_, body, content_type)) => {
                    Ok(served(body, content_type, ASSET_CACHE).into_response())
                }
                None => Err(warp::reject::not_found()),
            }
        });
    // Anything else is a mistyped address, and a person is reading it, so it
    // gets the page that says so rather than warp's bare 404.
    let missing = warp::any().map(|| {
        warp::reply::with_status(
            warp::reply::html(NOT_FOUND),
            warp::http::StatusCode::NOT_FOUND,
        )
    });

    overview
        .or(people)
        .or(island)
        .or(creator)
        .or(config)
        .or(assets)
        .or(missing)
        .map(|reply| Box::new(reply) as Box<dyn warp::Reply>)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn pages_are_served_with_their_content_types() {
        let filter = routes();
        for (path, kind, marker) in [
            ("/", "text/html", "id=\"activity\""),
            ("/people", "text/html", "id=\"roster\""),
            ("/creator", "text/html", "id=\"creator\""),
            ("/static/app.js", "text/javascript", "export"),
            ("/static/overview.js", "text/javascript", "/api/activity"),
            ("/static/people.js", "text/javascript", "/api/humans"),
            (
                "/static/creator.js",
                "text/javascript",
                "/api/creator/options",
            ),
            ("/static/style.css", "text/css", "prefers-color-scheme"),
        ] {
            let response = warp::test::request().path(path).reply(&filter).await;
            assert_eq!(response.status(), 200, "{path}");
            let content_type = response.headers()["content-type"].to_str().unwrap();
            assert!(content_type.starts_with(kind), "{path}: {content_type}");
            assert!(response.headers().contains_key("cache-control"), "{path}");
            let body = std::str::from_utf8(response.body()).unwrap();
            assert!(body.contains(marker), "{path} is missing {marker}");
        }
    }

    #[tokio::test]
    async fn an_unknown_page_says_so_in_words() {
        let filter = routes();
        for path in ["/nowhere", "/static/missing.js", "/people/extra"] {
            let response = warp::test::request().path(path).reply(&filter).await;
            assert_eq!(response.status(), 404, "{path}");
            let body = std::str::from_utf8(response.body()).unwrap();
            assert!(body.contains("</html>"), "{path} did not get the page");
        }
    }

    #[test]
    fn scripts_never_insert_markup() {
        // Names and attributes are user-supplied; text must go in as text.
        for (name, script, _) in ASSETS.iter().filter(|(name, _, _)| name.ends_with(".js")) {
            for banned in [
                "innerHTML",
                "outerHTML",
                "insertAdjacentHTML",
                "document.write",
            ] {
                assert!(!script.contains(banned), "{name} uses {banned}");
            }
        }
    }

    #[test]
    fn every_page_is_a_complete_document_in_plain_english() {
        for (name, html) in [
            ("index.html", OVERVIEW),
            ("people.html", PEOPLE),
            ("creator.html", CREATOR),
            ("not-found.html", NOT_FOUND),
        ] {
            assert!(html.starts_with("<!doctype html>"), "{name}");
            assert!(html.contains("<html lang=\"en\">"), "{name}");
            assert!(html.contains("name=\"viewport\""), "{name}: not responsive");
            assert!(html.contains("<title>"), "{name}: no title");
            assert!(html.contains("rel=\"stylesheet\""), "{name}");
            for placeholder in ["Lorem ipsum", "TODO", "FIXME", "TBD", "Coming soon"] {
                assert!(
                    !html.contains(placeholder),
                    "{name} still says {placeholder}"
                );
            }
        }
    }
}

/// Write the dashboard out as plain files.
///
/// The same bytes this binary serves, for a web server that is not this
/// one. Everything the pages need is here: the four pages, the not-found
/// page, the stylesheet, the scripts, and the generated `config.js` that
/// names the island they read.
///
/// Paths are flat and match what the pages ask for — `/static/app.js` is
/// written at `static/app.js` — so the directory can be served as-is.
/// `index.html` is at the root for a server that looks for one; the other
/// pages are written both as `people.html` and as `people/index.html`, so
/// the same directory works whether the host maps `/people` to a file or
/// to a directory. That is two copies of five small files, and it is the
/// difference between a frontend that works on any static host and one
/// that works on the half that happen to agree with this binary's routes.
pub fn export(to: &std::path::Path, backend: Backend) -> std::io::Result<usize> {
    use std::fs;

    let pages: [(&str, &str); 4] = [
        ("index", OVERVIEW),
        ("people", PEOPLE),
        ("island", ISLAND),
        ("creator", CREATOR),
    ];

    fs::create_dir_all(to)?;
    fs::create_dir_all(to.join("static"))?;
    let mut written = 0usize;

    for (name, body) in pages {
        fs::write(to.join(format!("{name}.html")), body)?;
        written += 1;
        // The overview is already `index.html`; the rest get a directory
        // of their own so `/people` resolves whichever way the host does
        // it.
        if name != "index" {
            fs::create_dir_all(to.join(name))?;
            fs::write(to.join(name).join("index.html"), body)?;
            written += 1;
        }
    }
    fs::write(to.join("404.html"), NOT_FOUND)?;
    written += 1;

    for (name, body, _) in ASSETS {
        fs::write(to.join("static").join(name), body)?;
        written += 1;
    }
    fs::write(to.join("static").join("config.js"), config_js(&backend))?;
    written += 1;

    Ok(written)
}

#[cfg(test)]
mod export_tests {
    use super::*;

    #[test]
    fn an_exported_dashboard_is_complete_and_knows_its_island() {
        let dir = tempfile::tempdir().unwrap();
        let written = export(dir.path(), Some("https://island.example".to_string())).unwrap();
        // Four pages, three of them written twice so `/people` resolves
        // whether the host wants a file or a directory, the not-found
        // page, every asset, and the generated config.
        assert_eq!(
            written,
            4 + 3 + 1 + ASSETS.len() + 1,
            "wrote {written} files"
        );

        // Every file a page asks for has to be there, at the path it asks
        // for it by. A missing one is a dashboard that loads and does
        // nothing, which is the failure this export exists to avoid.
        for page in ["index.html", "people.html", "island.html", "creator.html"] {
            let html = std::fs::read_to_string(dir.path().join(page)).unwrap();
            assert!(html.starts_with("<!doctype html>"), "{page}");
            for asset in ["/static/style.css", "/static/config.js"] {
                assert!(html.contains(asset), "{page} does not load {asset}");
            }
        }
        for name in ["people", "island", "creator"] {
            assert!(
                dir.path().join(name).join("index.html").is_file(),
                "a host that maps /{name} to a directory would 404"
            );
        }
        for (asset, _, _) in ASSETS {
            assert!(
                dir.path().join("static").join(asset).is_file(),
                "{asset} is missing"
            );
        }

        let config = std::fs::read_to_string(dir.path().join("static/config.js")).unwrap();
        assert!(
            config.contains("\"https://island.example\""),
            "the exported pages do not know which island to read: {config}"
        );
    }

    #[test]
    fn without_a_backend_the_export_reads_whoever_serves_it() {
        let dir = tempfile::tempdir().unwrap();
        export(dir.path(), None).unwrap();
        let config = std::fs::read_to_string(dir.path().join("static/config.js")).unwrap();
        assert!(config.contains("= \"\";"), "{config}");
    }
}
